#!/usr/bin/env sh

# Merged cronic and cronic-mail script
# Usage: cronic-mail CMD
# This script runs CMD, and emails the output if CMD fails or produces error output.

set -eu

usage() {
  echo "Usage: $(basename "$0") CMD" >&2
}

log() {
  echo "$*" >&2
}

resolve_mail_alias() {
  MAIL_ALIAS="$1"
  ALIAS_FILE="/etc/aliases"
  [ -z "$MAIL_ALIAS" ] && return 0
  [ ! -f "$ALIAS_FILE" ] && return 0
  awk -F ' *: *' -v al="$MAIL_ALIAS" \
    '$0 ~ "^" al " *:" { print $2; exit }' \
    "$ALIAS_FILE"
}

send_email() {
  {
    echo "Subject: Cronic detected failure in cron job: $*"
    [ -n "$MAILTO" ] && echo "To: $MAILTO"
    echo ""
    cat "$MAILFILE"
  } | {
    if [ -n "$DRY_RUN" ]
    then
      cat >&2 # output the email to stderr
    else
      sendmail "${MAILTO:-$USER}"
    fi
  }
}

if [ $# -eq 0 ]
then
  usage >&2
  exit 2
fi

DRY_RUN=${DRY_RUN:-}
USER=${USER:-$(id -un)}
MAILTO=${MAILTO:-$(resolve_mail_alias "$USER")}

TMPDIR=$(mktemp -d)
OUTFILE="${TMPDIR}/cronic.out"
ERRFILE="${TMPDIR}/cronic.err"
TRACEFILE="${TMPDIR}/cronic.trace"
MAILFILE="${TMPDIR}/cronic.mail"

# Execute the command
set +e
{
  "$@" >"$OUTFILE" 2>"$TRACEFILE"
  RC="$?"
}
set -e

# Assuming PS4 is '+', which is default in POSIX sh
PS4_PATTERN='^\+ '
if grep -Eaq "$PS4_PATTERN" "$TRACEFILE"
then
  grep -Eav "$PS4_PATTERN" "$TRACEFILE" > "$ERRFILE"
else
  ERRFILE="$TRACEFILE"
fi

if [ "$RC" -ne 0 ] || [ -s "$ERRFILE" ]
then
  {
    echo "Cronic detected failure or error output for the command:"
    echo "$*"
    echo

    echo "RETURN CODE: $RC"
    echo

    echo "STDERR:"
    cat "$ERRFILE"
    echo

    echo "STDOUT:"
    cat "$OUTFILE"
    echo

    if [ "$TRACEFILE" != "$ERRFILE" ]
    then
      echo "TRACE OUTPUT:"
      cat "$TRACEFILE"
      echo
    fi
  } > "$MAILFILE"

  # send mail
  send_email "$*"
fi

rm -rf "$TMPDIR"
