#!/usr/bin/env bash

usage() {
  echo "Usage: $(basename "$0") IP_ADDRESS"
}

reverse_resolve() {
  local target_ip="$1"

  # regular
  dig +short -x "$target_ip" &
  # netbird
  resolve_nb "$target_ip" &
  # tailscale
  resolve_ts "$target_ip" &
  # zerotier
  resolve_zt "$target_ip" &

  wait
}

resolve_nb() {
  local target_ip="$1"

  local nb_dns_port
  nb_dns_port=$(jq -er '
    .CustomDNSAddress // "127.0.0.1:11053" | split(":")[-1]
  ' /etc/netbird/config.json)

  # alternative:
  # ss -ulp | awk '/netbird/ && !/3128/ { print $4 }'
  # 127.0.0.1:11053

  dig +short @127.0.0.1 -p "$nb_dns_port" -x "$target_ip"
}

# Tailcale MagicDNS
# https://tailscale.com/kb/1081/magicdns
resolve_ts() {
  local target_ip="$1"
  dig +short @100.100.100.100 -x "$target_ip"
}

resolve_zt() {
  # TODO: We currently lack a local zerotier dns server
  # local target_ip="$1"
  # dig +short @127.0.0.1 -p changeme -x "$target_ip"
  echo "resolve_zt: NOT IMPLEMENTED" >&2
  return 1
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]
then
  IP="$1"

  if [[ -z $IP ]]
  then
    usage >&2
    exit 2
  fi

  RESULT=$(reverse_resolve "$IP" 2>/dev/null | sort -u)

  if [[ -z $RESULT ]]
  then
    echo "Failed to reserve resolve $IP" >&2
    exit 1
  fi

  echo "$RESULT"
  exit 0
fi
