#!/usr/bin/env sh

cd "$(dirname "$(readlink -f "$0")")" || return 9

DEST="${DEST:-/usr/local/bin}"
mkdir -p "$DEST"

find . \
  -mindepth 1 \
  -maxdepth 1 \
  -type f \
  -perm 755 \
  -exec sh -c 'fn="$(basename "$2")"; ln -sfv "$2" "$1/$fn"' shell "$DEST" {} \;
