#!/usr/bin/env bash

cd "$(dirname "$(readlink -f "$0")")" || return 9
# shellcheck source=lib/echo.sh
source lib/echo.sh || exit 2

tor::get-cookie-hex() {
  hexdump -ve '1/1 "%.2x"' "${TOR_COOKIE_FILE:-/var/lib/tor/control_auth_cookie}"
}

torctl() {
  local cookie_hex
  if ! cookie_hex="$(tor::get-cookie-hex)"
  then
    echo_error "Failed to read control auth cookie"
    return 1
  fi

  {
    printf 'AUTHENTICATE %s\r\n' "$cookie_hex"
    printf '%s\r\n' "$@"
    printf 'QUIT\r\n'
  } | nc 127.0.0.1 9051
}

tor::request-new-identity() {
  torctl 'SIGNAL NEWNYM'
}

main() {
  tor::request-new-identity
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]
then
  main "$@"
fi
