#!/usr/bin/env bash

usage() {
  echo "Usage: $0 [--raw-output] CONFIG_SECTION [JSON_PATH]"
  echo "Examples:"
  echo " - $0 --list"
  echo " - $0 dhcp"
  echo " - $0 --raw network lan.ipaddr"
}

uci_list_configs() {
  uci show | cut -d. -f1 | sort -u
}

uci_json() {
  local config="$1"
  local json_path="$2"

  local request
  request=$(jq -ncer --arg config "$config" '{ config: $config }')

  ubus call uci get "$request" | \
    jq -e ${JQ_RAW:+--raw-output} --arg path "$json_path" '
      .values

      | if ($path | length) > 0
        then
          ($path | split(".") | map(select(length > 0))) as $keys
          | getpath($keys) // empty
        end
    '
}

main() {
  local args
  while [[ -n "$*" ]]
  do
    case "$1" in
      help|h|-h|--help)
        usage
        return 0
        ;;
      list|-l|--list)
        uci_list_configs
        return 0
        ;;
      -r|--raw|--raw-output)
        JQ_RAW=1
        shift
        ;;
      --)
        shift
        break
        ;;
      *)
        args+=("$1")
        shift
        ;;
    esac
  done

  set -- "${args[@]}"

  local config="$1"
  local json_path="$2"

  if [[ -z "$config" ]]
  then
    {
      echo "Error: CONFIG_path is required."
      usage
      echo "Available configurations:"
      uci_list_configs
    } >&2
    return 2
  fi

  uci_json "$config" "$json_path"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]
then
  main "$@"
fi
